// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace, KvNamespace as __TelnyxKvNamespace } from "@telnyx/edge-runtime";
import type { PatientActor } from "./src/index";
import type { default as __TelnyxClient } from "telnyx";

declare global {
  interface Env {
    PATIENT: __TelnyxActorNamespace<PatientActor>;
    telnyx: __TelnyxClient;
    DEPARTMENT_KV: __TelnyxKvNamespace;
    SECRETS: { get(binding: "TELNYX_PUBLIC_KEY"): Promise<string> };
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    PATIENT: __TelnyxActorNamespace<PatientActor>;
    telnyx: __TelnyxClient;
    DEPARTMENT_KV: __TelnyxKvNamespace;
    SECRETS: { get(binding: "TELNYX_PUBLIC_KEY"): Promise<string> };
  }
}

export {};
